from models import Movie

MOVIES = [
    Movie(
        id=1,
        title="The Shawshank Redemption",
        year=1994,
        director="Frank Darabont",
        genres=["Drama"],
        rating=9.3,
        description="Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    ),
    Movie(
        id=2,
        title="The Godfather",
        year=1972,
        director="Francis Ford Coppola",
        genres=["Crime", "Drama"],
        rating=9.2,
        description="The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
    ),
    Movie(
        id=3,
        title="The Dark Knight",
        year=2008,
        director="Christopher Nolan",
        genres=["Action", "Crime", "Drama"],
        rating=9.0,
        description="Batman raises the stakes in his war on crime, confronting the Joker, a criminal mastermind who plunges Gotham into chaos.",
    ),
    Movie(
        id=4,
        title="Pulp Fiction",
        year=1994,
        director="Quentin Tarantino",
        genres=["Crime", "Drama"],
        rating=8.9,
        description="The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    ),
    Movie(
        id=5,
        title="Inception",
        year=2010,
        director="Christopher Nolan",
        genres=["Action", "Adventure", "Sci-Fi"],
        rating=8.8,
        description="A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into a target's mind.",
    ),
    Movie(
        id=6,
        title="Interstellar",
        year=2014,
        director="Christopher Nolan",
        genres=["Adventure", "Drama", "Sci-Fi"],
        rating=8.7,
        description="A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    ),
    Movie(
        id=7,
        title="Parasite",
        year=2019,
        director="Bong Joon-ho",
        genres=["Comedy", "Drama", "Thriller"],
        rating=8.5,
        description="Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    ),
    Movie(
        id=8,
        title="The Matrix",
        year=1999,
        director="The Wachowskis",
        genres=["Action", "Sci-Fi"],
        rating=8.7,
        description="A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    ),
    Movie(
        id=9,
        title="Schindler's List",
        year=1993,
        director="Steven Spielberg",
        genres=["Biography", "Drama", "History"],
        rating=9.0,
        description="In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution.",
    ),
    Movie(
        id=10,
        title="Spirited Away",
        year=2001,
        director="Hayao Miyazaki",
        genres=["Animation", "Adventure", "Family"],
        rating=8.6,
        description="During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    ),
]
